pub mod allocation;
pub mod audit_log;
pub mod auth;
pub mod cash_flow;
pub mod ctc;
pub mod dashboard;
pub mod department;
pub mod holiday;
pub mod project;
pub mod resource;
pub mod team;
pub mod thr;
pub mod user;

pub use allocation::allocation_routes;
pub use audit_log::audit_log_routes;
pub use auth::{auth_routes, Claims};
pub use cash_flow::cash_flow_routes;
pub use ctc::ctc_routes;
pub use dashboard::dashboard_routes;
pub use department::department_routes;
pub use holiday::holiday_routes;
pub use project::project_routes;
pub use resource::resource_routes;
pub use team::team_routes;
pub use thr::thr_routes;
pub use user::user_routes;
